name: presentation

version: 1.0.0+1
description: "presentation layer"
publish_to: 'none'
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  domain:
    path: ../domain

  cupertino_icons: ^1.0.2

  bloc: ^7.2.1
  flutter_bloc: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
