name: 'application'
description: "Clean architecture approach example"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  get_it: ^7.2.0

  flutter:
    sdk: flutter

  web_gateway:
    path: ./layers/web_gateway

  mobile_gateway:
    path: ./layers/mobile_gateway

  domain:
    path: ./layers/domain

  mobile_presentation:
    path: ./layers/mobile_presentation

  web_presentation:
    path: ./layers/web_presentation

flutter:
  uses-material-design: true
