name: 'generic_blocs'

version: 1.0.0+1
description: "Generic blocs which can be used by any UI module"
publish_to: 'none'
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^7.2.1

  domain:
    path: ../domain
