name: 'web_gateway'

version: 1.0.0+1
description: "data layer"
publish_to: none
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  get_it: ^7.2.0
  rxdart: ^0.27.2

  domain:
    path: ../domain

  uuid: ">=3.0.5"